module.exports = {
  // bs_chrome: {
  //   base: "BrowserStack",
  //   browser: "Chrome",
  //   browser_version: "latest",
  //   os: "Windows",
  //   os_version: "10",
  // },
  // bs_firefox: {
  //   base: "BrowserStack",
  //   browser: "Firefox",
  //   browser_version: "latest",
  //   os: "Windows",
  //   os_version: "10",
  // },
  // bs_edge: {
  //   base: "BrowserStack",
  //   browser: "Edge",
  //   browser_version: "latest",
  //   os: "Windows",
  //   os_version: "10",
  // },
  bs_ie11: {
    base: "BrowserStack",
    browser: "IE",
    browser_version: "11.0",
    os: "Windows",
    os_version: "10",
  },
  bs_ie10: {
    base: "BrowserStack",
    browser: "IE",
    browser_version: "10.0",
    os: "Windows",
    os_version: "8",
  },
  // bs_safari: {
  //   base: "BrowserStack",
  //   browser: "Safari",
  //   browser_version: "latest",
  //   os: "OS X",
  //   os_version: "Mojave",
  // },
  // sl_ios: {
  //   base: 'SauceLabs',
  //   platform: 'iOS',
  //   device: 'iPhone X Simulator',
  //   browserName: 'safari',
  //   version: '12.2',
  // },
  // sl_android_8: {
  //   base: 'SauceLabs',
  //   platform: 'Android',
  //   device: 'Android Emulator',
  //   browserName: 'chrome',
  //   version: '8.0',
  // },
  // sl_android_6: {
  //   base: 'SauceLabs',
  //   platform: 'Android',
  //   device: 'Android Emulator',
  //   browserName: 'chrome',
  //   version: '6.0',
  // },
  // sl_android_5: {
  //   base: 'SauceLabs',
  //   platform: 'Android',
  //   device: 'Android Emulator',
  //   browserName: 'browser',
  //   version: '5.1',
  // },
};
